<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateStudentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('students', function (Blueprint $table) {
            $table->id();
            $table->string('active', 255)->nullable()->default('');
            $table->string('name', 255)->nullable()->default('');
            $table->string('bsms_id', 255)->nullable()->default('');
            $table->unsignedInteger('student_number')->nullable();
            $table->string('first_name', 255)->nullable()->default('');
            $table->string('known_as', 255)->nullable()->default('');
            $table->date('dob')->nullable();
            $table->string('email', 255)->nullable()->default('');
            $table->string('rotation_group', 255)->nullable()->default('');
            $table->integer('year')->nullable();
            $table->string('age', 255);
            $table->string('gender', 255);
            $table->string('car_owner', 255);
            $table->string('gp_teacher', 255)->nullable()->default('');
            $table->unsignedBigInteger('placements_id')->nullable();
            $table->integer('facilitator_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->unsignedBigInteger('locations_id');
            $table->nullableTimestamps();
            $table->unsignedBigInteger('gp_teacher_id');
            $table->text('notes')->nullable();
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('students');
    }
}
