<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFacilitatorsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('facilitators', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('bsmsID', 255);
            $table->string('Firstname', 255);
            $table->string('Surname', 255);
            $table->string('KnownAS', 255);
            $table->string('EmailAddress', 255);
            $table->string('Address', 255);
            $table->string('Designation', 255);
            $table->string('Qualification', 255);
            $table->dateTime('JoiningDate')->default(\DB::raw('CURRENT_TIMESTAMP'));
            $table->string('TeachingSubject', 255);
            $table->tinyInteger('Status')->nullable()->default(0);
            $table->timestamps();
            $table->string('active', 3);
            $table->unique('bsmsID', 'facilitators_bsmsid_unique');
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('facilitators');
    }
}
