<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateGpTeachersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('gp_teachers', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('bsms_id', 255);
            $table->string('firstname', 255);
            $table->string('surname', 255);
            $table->string('known_as', 255);
            $table->string('email', 255);
            $table->string('address', 255);
            $table->string('nhs_id', 255);
            $table->integer('designation');
            $table->string('qualification', 255);
            $table->string('joining_date', 255);
            $table->string('leaving_date', 255);
            $table->string('teaching_subject', 255);
            $table->string('status', 255);
            $table->rememberToken();
            $table->nullableTimestamps();
            $table->unsignedBigInteger('rooms_id');
            $table->unsignedBigInteger('workshops_id');
            $table->string('active', 3)->nullable();
            $table->unique('bsms_id', 'gpteachers_bsmsid_unique');
            $table->index('rooms_id', 'gp_teachers_rooms_id_foreign');
            $table->index('workshops_id', 'gp_teachers_workshops_id_foreign');
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('gp_teachers');
    }
}
