<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateMonitoredSessions2026Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('MonitoredSessions2026', function (Blueprint $table) {
            $table->bigInteger('ID')->primary();
            $table->string('ModuleCode', 21);
            $table->string('SessionTitle', 86);
            $table->string('ClinicalSubType', 26)->nullable();
        });

        // Insert data in chunks
        $sessions = [
            ['ID' => 1, 'ModuleCode' => 'BSMS001 test sessions', 'SessionTitle' => 'Staff Logged Test Session', 'ClinicalSubType' => 'Test session'],
            ['ID' => 2, 'ModuleCode' => 'BSMS001 test sessions', 'SessionTitle' => 'Student Logged Test Session', 'ClinicalSubType' => 'Test session'],
            ['ID' => 3, 'ModuleCode' => 'BSMS110', 'SessionTitle' => 'IIH 1 - Seminar - Inequality and Health', 'ClinicalSubType' => null],
            ['ID' => 4, 'ModuleCode' => 'BSMS110', 'SessionTitle' => 'IIH 2 - Seminar - Race and Health', 'ClinicalSubType' => null],
            ['ID' => 5, 'ModuleCode' => 'BSMS110', 'SessionTitle' => 'IIH 3 - Seminar - Gender and Health', 'ClinicalSubType' => null],
            ['ID' => 6, 'ModuleCode' => 'BSMS110', 'SessionTitle' => 'IIH 4 - Seminar - Environment and Health', 'ClinicalSubType' => null],
            ['ID' => 7, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'IIH 1 - Seminar - Social Exclusion and Health', 'ClinicalSubType' => null],
            ['ID' => 8, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Week 1 - Lecture - Introduction to Time for Dementia', 'ClinicalSubType' => null],
            ['ID' => 9, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Week 5- Seminar - Emotions and Wellbeing', 'ClinicalSubType' => null],
            ['ID' => 10, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Immersion Week - Seminar - Teamworking', 'ClinicalSubType' => null],
            ['ID' => 11, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Immersion Week - Seminar - Medical Law', 'ClinicalSubType' => null],
            ['ID' => 12, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'IIH 2 - Seminar - Professionalism and Systemic Racism', 'ClinicalSubType' => null],
            ['ID' => 13, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 1 - Seminar - Introduction to Module 101', 'ClinicalSubType' => null],
            ['ID' => 14, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 1 - Lecture - Module Lead Introduction', 'ClinicalSubType' => null],
            ['ID' => 15, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 2 - Seminar - Consulting with Patients 1', 'ClinicalSubType' => null],
            ['ID' => 16, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 2 - Lecture - Introduction to Ethics', 'ClinicalSubType' => null],
            ['ID' => 17, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 3 - CPW 1 - History Taking', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 18, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 3 - Symposium - Child and Family 1 Pt1', 'ClinicalSubType' => null],
            ['ID' => 19, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 3 - Symposium - Child and Family 1 Pt2', 'ClinicalSubType' => null],
            ['ID' => 20, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 4 - Seminar - Consulting with Patients 2', 'ClinicalSubType' => null],
            ['ID' => 21, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 4 - Symposium - Child and Family 2 Pt1', 'ClinicalSubType' => null],
            ['ID' => 22, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 4 - Symposium - Child and Family 2 Pt2', 'ClinicalSubType' => null],
            ['ID' => 23, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 5  - Lecture - Public Health 1', 'ClinicalSubType' => null],
            ['ID' => 24, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 5 - Symposium - Child and Family 3 Pt1', 'ClinicalSubType' => null],
            ['ID' => 25, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 5 - Symposium - Child and Family 3 Pt2', 'ClinicalSubType' => null],
            ['ID' => 26, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 6 - CPW 2 - Signs and Symptoms', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 27, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 7 - Seminar - Reflective Practice 1', 'ClinicalSubType' => null],
            ['ID' => 28, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 8 - Seminar - Child and Family 4', 'ClinicalSubType' => null],
            ['ID' => 29, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 9 - Seminar - Reflective Practice 2', 'ClinicalSubType' => null],
            ['ID' => 30, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 15 - Lecture - Child and Family Safeguarding', 'ClinicalSubType' => null],
            ['ID' => 31, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 15 - Seminar - Child and Family Safeguarding', 'ClinicalSubType' => null],
            ['ID' => 32, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 16 - CPW 3 - CVS History Taking', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 33, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 17 - Symposium - Introduction to Pharmacological Medicine Pt1', 'ClinicalSubType' => null],
            ['ID' => 34, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 18 - CPW 4 - CVS Examination', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 35, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 19 - Seminar - Consulting with Patients 3', 'ClinicalSubType' => null],
            ['ID' => 36, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 20 - CPW 5 - Respiratory History Taking', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 37, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 21 - Symposium - Alcoholism and Recovery Pt1', 'ClinicalSubType' => null],
            ['ID' => 38, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 22 - CPW 6 - Respiratory Examination', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 39, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 17 - Symposium - Introduction to Pharmacological Medicine Pt2', 'ClinicalSubType' => null],
            ['ID' => 40, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 27 - CPW 7 - Gastrointestinal History Taking', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 41, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 30 - Lecture - Public Health 3', 'ClinicalSubType' => null],
            ['ID' => 42, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 31 - Symposium - Burns Treatment and Care in an MDT Pt1', 'ClinicalSubType' => null],
            ['ID' => 43, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 35 - Symposium - Burns Treatment and Care in an MDT Pt2', 'ClinicalSubType' => null],
            ['ID' => 44, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 32 - Lecture - Health Risks and Behaviours', 'ClinicalSubType' => null],
            ['ID' => 45, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 32 - Seminar - Health Risks and Behaviours', 'ClinicalSubType' => null],
            ['ID' => 46, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 33 - CPW 9 - Focussed History Taking / SOCRATES', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 47, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Introductory Formative OSCE', 'ClinicalSubType' => 'POSCE'],
            ['ID' => 48, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Week 29 - CPW 8 - Gastrointestinal Examination', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 49, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 21 - Symposium - Alcoholism and Recovery Pt2', 'ClinicalSubType' => null],
            ['ID' => 50, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 17 - Symposium - Ethics 2: Developing Moral Vision', 'ClinicalSubType' => null],
            ['ID' => 51, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 21 -  Lecture - Public Health 2', 'ClinicalSubType' => null],
            ['ID' => 52, 'ModuleCode' => 'BSMS101', 'SessionTitle' => 'Week 29 - Symposium - Ethics 3: Equality and Diversity in Healthcare', 'ClinicalSubType' => null],
            ['ID' => 53, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'CTS 1 - Infection Control and Prevention', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 54, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'GP Placement - Visit 1', 'ClinicalSubType' => 'General Practice'],
            ['ID' => 55, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'GP Placement - Visit 2', 'ClinicalSubType' => 'General Practice'],
            ['ID' => 56, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Simulated Home - Visit 1', 'ClinicalSubType' => 'Simulation Flat'],
            ['ID' => 57, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Adult Basic Life Support', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 58, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'CTS 2 - NEWS and Observations', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 59, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'IA - Communication Skills', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 60, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'IA - History Taking', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 61, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'IA - A-E Approach', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 62, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'CTS 3 - Initial Assessment, A-E Approach and Airway', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 63, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Simulated Home - Visit 2', 'ClinicalSubType' => 'Simulation Flat'],
            ['ID' => 64, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'CTS 2 Lecture - NEWS and Observations', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 65, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'CTS 3 Lecture  - Initial Assessment, A-E Approach and Airway', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 66, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'IIH 3 - LGBTQ+ and Health', 'ClinicalSubType' => null],
            ['ID' => 67, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'IIH 4- Disability and Stigma', 'ClinicalSubType' => null],
            ['ID' => 68, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Seminar - Medical Professionalism', 'ClinicalSubType' => null],
            ['ID' => 69, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'IIH 5- Seminar-Learning Disability and Health', 'ClinicalSubType' => null],
            ['ID' => 70, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 1 - CPW 1 - Resp/CVS/Abdo History Taking Recap', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 71, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'Introduction to Year 2', 'ClinicalSubType' => null],
            ['ID' => 72, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'MyStudies, Library Refresher and Sofia Demo', 'ClinicalSubType' => null],
            ['ID' => 73, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'Introduction to Module 202', 'ClinicalSubType' => null],
            ['ID' => 74, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'Attendance, Engagement and Professionalism', 'ClinicalSubType' => null],
            ['ID' => 75, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'Assessment Overview', 'ClinicalSubType' => null],
            ['ID' => 76, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'Student Wellbeing and Advice Introduction', 'ClinicalSubType' => null],
            ['ID' => 77, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 PC1 Skull and Cranial Cavity', 'ClinicalSubType' => null],
            ['ID' => 78, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'GMC Update', 'ClinicalSubType' => null],
            ['ID' => 79, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 Symposium 1: An Analysis of Stroke and Sequelae – Part 1', 'ClinicalSubType' => null],
            ['ID' => 80, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 Symposium 1: An Analysis of Stroke and Sequelae – Part 2', 'ClinicalSubType' => null],
            ['ID' => 81, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 PC2 Organisation of the Central Nervous System 1', 'ClinicalSubType' => null],
            ['ID' => 82, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 MT3 Falls as Autonomic and Cerebellar Malfunction', 'ClinicalSubType' => null],
            ['ID' => 83, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC5 Orbit and Nasal Cavity', 'ClinicalSubType' => null],
            ['ID' => 84, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 MT2 Action Potentials', 'ClinicalSubType' => null],
            ['ID' => 85, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 Mini Symposium 2: Migraines and Headaches', 'ClinicalSubType' => null],
            ['ID' => 86, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 4: Neurodivergence in Clinical Practice – Part 1', 'ClinicalSubType' => null],
            ['ID' => 87, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 4: Neurodivergence in Clinical Practice – Part 2', 'ClinicalSubType' => null],
            ['ID' => 88, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC4 Organization of the Central Nervous System 2', 'ClinicalSubType' => null],
            ['ID' => 89, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC6 Human Vision Lab', 'ClinicalSubType' => null],
            ['ID' => 90, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC7 Face, Temporal and Infratemporal Fossa', 'ClinicalSubType' => null],
            ['ID' => 91, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC8 Neck and Oral Cavity', 'ClinicalSubType' => null],
            ['ID' => 92, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T2 PC9 Human Hearing Lab', 'ClinicalSubType' => null],
            ['ID' => 93, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 3: The Generation of Seizures and Mechanisms Underlying Epilepsy – Part 1', 'ClinicalSubType' => null],
            ['ID' => 94, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 3: The Generation of Seizures and Mechanisms Underlying Epilepsy – Part 2', 'ClinicalSubType' => null],
            ['ID' => 95, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 5: Illicit Substance Misuse – Part 1', 'ClinicalSubType' => null],
            ['ID' => 96, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 5: Illicit Substance Misuse – Part 2', 'ClinicalSubType' => null],
            ['ID' => 97, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 MT1 Living Anatomy and Ultrasound of the Head and Neck', 'ClinicalSubType' => null],
            ['ID' => 98, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T1 PC3 Imaging of the Brain and the Spinal Cord', 'ClinicalSubType' => null],
            ['ID' => 99, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 6: Management of and Recovery from Psychosis – Part 1', 'ClinicalSubType' => null],
            ['ID' => 100, 'ModuleCode' => 'BSMS202', 'SessionTitle' => 'T3 Symposium 6: Management of and Recovery from Psychosis – Part 2', 'ClinicalSubType' => null],
            ['ID' => 101, 'ModuleCode' => 'BSMS101 Clinical', 'SessionTitle' => 'Weeks 25 & 26 - Communication Skills - Consulting with Patients 4', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 102, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 4 - CPW 3 - Localisation in Neurology', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 103, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 2 - CPW 2 - Resp/CVS/Abdo Examination Recap', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 104, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 7 - CPW 4 - Cranial Nerves', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 105, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 10 - CPW 5 - Clinical Skills in Psychiatry', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 106, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 8/9 - CPW 6 - Peripheral Nervous System Examination Skills', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 107, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 15 - CPW 7 - The Locomotor System Part 1', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 108, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 16 - CPW 8 - The Locomotor System Part 2', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 109, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 20 - CPW 9 - GALS and MSK Examination Skills', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 110, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 28 - CPW 10 - Gynae and Pelvis Examination Skills', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 111, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 33/34 - CPW 11 - History Taking and Examination Skills Revision', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 112, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 1 - Lecture - Introduction to the Module', 'ClinicalSubType' => null],
            ['ID' => 113, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Ethics and Medicine 1', 'ClinicalSubType' => null],
            ['ID' => 114, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 1 - Symposium - Communication and Deafness Pt1', 'ClinicalSubType' => null],
            ['ID' => 115, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 1 - Symposium - Communication and Deafness Pt2', 'ClinicalSubType' => null],
            ['ID' => 116, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - Lecture - Critical Care', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 117, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 1 - Symposium - Clinical Therapeutics 1 Pt1', 'ClinicalSubType' => null],
            ['ID' => 118, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 1 - Symposium - Clinical Therapeutics 1 Pt2', 'ClinicalSubType' => null],
            ['ID' => 119, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 21 - Symposium - Clinical Therapeutics 2 Pt1', 'ClinicalSubType' => null],
            ['ID' => 120, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 21 - Symposium - Clinical Therapeutics 2 Pt2', 'ClinicalSubType' => null],
            ['ID' => 121, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 22 - Symposium - Clinical Therapeutics 3 Pt1', 'ClinicalSubType' => null],
            ['ID' => 122, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 22 - Symposium - Clinical Therapeutics 3 Pt2', 'ClinicalSubType' => null],
            ['ID' => 123, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 17 - Lecture - Ethics and Medicine 2', 'ClinicalSubType' => null],
            ['ID' => 124, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 3 - Seminar - Healthcare Systems and Primary Care', 'ClinicalSubType' => null],
            ['ID' => 125, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 18 - Seminar - Communication: Challenging Circumstances', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 126, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 21 - Seminar - Communication: Breaking Bad News', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 127, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 22 - Seminar - Ageing and Ageism', 'ClinicalSubType' => null],
            ['ID' => 128, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 23 - Seminar - End of Life: Care Considerations', 'ClinicalSubType' => null],
            ['ID' => 129, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 29 - Seminar - Communication: Sexual Health Medicine', 'ClinicalSubType' => null],
            ['ID' => 130, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 30 - Lecture - Sustainability in Healthcare', 'ClinicalSubType' => null],
            ['ID' => 131, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Week 30 - Seminar - Sustainability in Healthcare', 'ClinicalSubType' => null],
            ['ID' => 132, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Week 32 - Seminar - Communication: Consultation Skills', 'ClinicalSubType' => 'Clinical Practice Workshop'],
            ['ID' => 133, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Community Hospital - Visit 1', 'ClinicalSubType' => 'Community Hospital'],
            ['ID' => 134, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Community Hospital - Visit 2', 'ClinicalSubType' => 'Community Hospital'],
            ['ID' => 135, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Community Hospital - Visit 3', 'ClinicalSubType' => 'Community Hospital'],
            ['ID' => 136, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS 1 - ECG and Blood Glucose', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 137, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS 2 - IM Injection and ABLS Refresher', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 138, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS 3 - Wound Assessment/Closure and Inhaled Medication', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 139, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS 4 - Paeds BLS and NEWS', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 140, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS 5 - OSCE Preparation', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 141, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'CTS - Lecture - OSCE Preparation', 'ClinicalSubType' => 'Clinical Technical Skills'],
            ['ID' => 142, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - Visit - Critical Care', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 143, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - Immersive ED', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 144, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - ABCDE', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 145, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - Immersion - Physiology SiM', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 146, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - VCE', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 147, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Lecture - Monday', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 148, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Seminar - Monday', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 149, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Patient Case Assignment', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 150, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Seminar - Tuesday', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 151, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Lecture - Psychiatry', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 152, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - Seminar - Psychiatry', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 153, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - GP Teaching - CBD Presentations', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 154, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'IA - VCE', 'ClinicalSubType' => 'Initial Assessment'],
            ['ID' => 155, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - IPE - Tuesday Activity', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 156, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - IPE - Wednesday Activity', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 157, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - IPE - Thursday Activity', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 158, 'ModuleCode' => 'BSMS201', 'SessionTitle' => 'Immersion Week - IPE - Friday Presentation', 'ClinicalSubType' => 'By Rotation'],
            ['ID' => 159, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - Community Placement - Monday', 'ClinicalSubType' => 'Immersion Community'],
            ['ID' => 160, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - Community Placement - Wednesday', 'ClinicalSubType' => 'Immersion Community'],
            ['ID' => 161, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - Community Placement - Thursday', 'ClinicalSubType' => 'Immersion Community'],
            ['ID' => 162, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - Community Placement - Friday', 'ClinicalSubType' => 'Immersion Community'],
            ['ID' => 163, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - GP Placement - Day 1', 'ClinicalSubType' => 'General Practice'],
            ['ID' => 164, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - GP Placement - Day 2', 'ClinicalSubType' => 'General Practice'],
            ['ID' => 165, 'ModuleCode' => 'BSMS201 Clinical', 'SessionTitle' => 'Immersion - GP Placement - Day 3', 'ClinicalSubType' => 'General Practice'],
            ['ID' => 166, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Introduction to assessment in year 1 of BSMS', 'ClinicalSubType' => null],
            ['ID' => 167, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Introduction to BSMS Module 102', 'ClinicalSubType' => null],
            ['ID' => 168, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC1', 'ClinicalSubType' => null],
            ['ID' => 169, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC2', 'ClinicalSubType' => null],
            ['ID' => 170, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC3', 'ClinicalSubType' => null],
            ['ID' => 171, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC4', 'ClinicalSubType' => null],
            ['ID' => 172, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC5', 'ClinicalSubType' => null],
            ['ID' => 173, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC6', 'ClinicalSubType' => null],
            ['ID' => 174, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC7', 'ClinicalSubType' => null],
            ['ID' => 175, 'ModuleCode' => 'BSMS202 SSC', 'SessionTitle' => 'SSC8', 'ClinicalSubType' => null],
            ['ID' => 176, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Immersion Week - Lecture - Teamworking', 'ClinicalSubType' => null],
            ['ID' => 177, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Immersion Week - Lecture - Medical Law', 'ClinicalSubType' => null],
            ['ID' => 178, 'ModuleCode' => 'BSMS210', 'SessionTitle' => 'Lecture- Ethicial Perspectives on Current Issues in Clinical Practice.', 'ClinicalSubType' => null],
            ['ID' => 179, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 1', 'ClinicalSubType' => null],
            ['ID' => 180, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Suicide Awareness', 'ClinicalSubType' => null],
            ['ID' => 181, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 Symposium 1: The anatomical donor and body donation - Part 1', 'ClinicalSubType' => null],
            ['ID' => 182, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 Symposium 1: The anatomical donor and body donation - Part 2', 'ClinicalSubType' => null],
            ['ID' => 183, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 2', 'ClinicalSubType' => null],
            ['ID' => 184, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 DR1: Introduction to dissection', 'ClinicalSubType' => null],
            ['ID' => 185, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 3', 'ClinicalSubType' => null],
            ['ID' => 186, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 1: Introduction to microscopic anatomy - Part 1', 'ClinicalSubType' => null],
            ['ID' => 187, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 1: Introduction to microscopic anatomy - Part 2', 'ClinicalSubType' => null],
            ['ID' => 188, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 MT1: Cell structure, transcription, translation and protein structure', 'ClinicalSubType' => null],
            ['ID' => 189, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T2 Module Tutorial', 'ClinicalSubType' => null],
            ['ID' => 190, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 Symposium 1: Genomic testing - Marfan\'s syndrome - Part 1', 'ClinicalSubType' => null],
            ['ID' => 191, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 Symposium 1: Genomic testing - Marfan\'s syndrome - Part 2', 'ClinicalSubType' => null],
            ['ID' => 192, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T4 MT1: Transmission, incubation period and spread of infectious agents', 'ClinicalSubType' => null],
            ['ID' => 193, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 2: The skin - Part 1', 'ClinicalSubType' => null],
            ['ID' => 194, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 2: The skin - Part 2', 'ClinicalSubType' => null],
            ['ID' => 195, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 4', 'ClinicalSubType' => null],
            ['ID' => 196, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Phase Leader Forum', 'ClinicalSubType' => null],
            ['ID' => 197, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T2 Symposium: What is healthy? What is normal? - Part 1', 'ClinicalSubType' => null],
            ['ID' => 198, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T2 Symposium: What is healthy? What is normal? - Part 2', 'ClinicalSubType' => null],
            ['ID' => 199, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 DR2: Thoracic wall', 'ClinicalSubType' => null],
            ['ID' => 200, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 5', 'ClinicalSubType' => null],
            ['ID' => 201, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 MT2: Cellular communication, receptors and drug action', 'ClinicalSubType' => null],
            ['ID' => 202, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 3: Inflammation - Part 1', 'ClinicalSubType' => null],
            ['ID' => 203, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 PIC 3: Inflammation - Part 2', 'ClinicalSubType' => null],
            ['ID' => 204, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T4 Symposium: Commensalism and pathogenesis - Part 1', 'ClinicalSubType' => null],
            ['ID' => 205, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T4 Symposium: Commensalism and pathogenesis - Part 2', 'ClinicalSubType' => null],
            ['ID' => 206, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'Academic Skills 6', 'ClinicalSubType' => null],
            ['ID' => 207, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T4 Microbiology Practical', 'ClinicalSubType' => null],
            ['ID' => 208, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 Living Anatomy/Ultrasound - Landmarks of the chest wall', 'ClinicalSubType' => null],
            ['ID' => 209, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 Symposium 2:  \nChronic lymphocytic leukaemia - diagnosis and treatment - Part 1', 'ClinicalSubType' => null],
            ['ID' => 210, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T3 Symposium 2:  \nChronic lymphocytic leukaemia - diagnosis and treatment - Part 2', 'ClinicalSubType' => null],
            ['ID' => 211, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T4 MT2: Viruses and how they work - principles of immunity', 'ClinicalSubType' => null],
            ['ID' => 212, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 DR3: Applied Anatomy/Revision', 'ClinicalSubType' => null],
            ['ID' => 213, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 DR4: Formative Spotter', 'ClinicalSubType' => null],
            ['ID' => 214, 'ModuleCode' => 'BSMS202', 'SessionTitle' => '202 Phase Leader Forum', 'ClinicalSubType' => null],
            ['ID' => 215, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 Symposium 2: Imaging the living human body - Part 1', 'ClinicalSubType' => null],
            ['ID' => 216, 'ModuleCode' => 'BSMS102', 'SessionTitle' => 'T1 Symposium 2: Imaging the living human body - Part 2', 'ClinicalSubType' => null],
            ['ID' => 217, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 1', 'ClinicalSubType' => null],
            ['ID' => 218, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 2', 'ClinicalSubType' => null],
            ['ID' => 219, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 3', 'ClinicalSubType' => null],
            ['ID' => 220, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 4', 'ClinicalSubType' => null],
            ['ID' => 221, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 5', 'ClinicalSubType' => null],
            ['ID' => 222, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 6', 'ClinicalSubType' => null],
            ['ID' => 223, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 7', 'ClinicalSubType' => null],
            ['ID' => 224, 'ModuleCode' => 'BSMS103 SSC', 'SessionTitle' => 'SSC 8', 'ClinicalSubType' => null],
            ['ID' => 225, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Introduction and Preparation for Poster Assessment', 'ClinicalSubType' => null],
            ['ID' => 226, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR1: Back and Shoulder', 'ClinicalSubType' => null],
            ['ID' => 227, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR2: The Arm and Brachial Plexus', 'ClinicalSubType' => null],
            ['ID' => 228, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR3: The Forearm', 'ClinicalSubType' => null],
            ['ID' => 229, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'MT1: Joint Pain', 'ClinicalSubType' => null],
            ['ID' => 230, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Phase Leader Forum', 'ClinicalSubType' => null],
            ['ID' => 231, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 1: Osteoporosis, Nutrition and Fragility Fractures - Part 1', 'ClinicalSubType' => null],
            ['ID' => 232, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 1: Osteoporosis, Nutrition and Fragility Fractures - Part 2', 'ClinicalSubType' => null],
            ['ID' => 233, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR4: The Hand', 'ClinicalSubType' => null],
            ['ID' => 234, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'MT2: Living Anatomy', 'ClinicalSubType' => null],
            ['ID' => 235, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR5: Gluteal Region and Thigh', 'ClinicalSubType' => null],
            ['ID' => 236, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'MT3: Immunology of Infection', 'ClinicalSubType' => null],
            ['ID' => 237, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'DR6: Knee and Leg', 'ClinicalSubType' => null],
            ['ID' => 238, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 2: Systemic Inflammatory Disease - Part 1', 'ClinicalSubType' => null],
            ['ID' => 239, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'MT4: Living Anatomy of the Lower Limb', 'ClinicalSubType' => null],
            ['ID' => 240, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 3: HIV and Immunology - Part 1', 'ClinicalSubType' => null],
            ['ID' => 241, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 2: Systemic Inflammatory Disease - Part 2', 'ClinicalSubType' => null],
            ['ID' => 242, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Symposium 3: HIV and Immunology - Part 2', 'ClinicalSubType' => null],
            ['ID' => 243, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'Introduction to Module 103', 'ClinicalSubType' => null],
            ['ID' => 244, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 DR1 Dissection of The Lungs and Pleura', 'ClinicalSubType' => null],
            ['ID' => 245, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'FMA 1', 'ClinicalSubType' => null],
            ['ID' => 246, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 DR2 Examination of the Pericardium and Features of the Heart', 'ClinicalSubType' => null],
            ['ID' => 247, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T3 PC1 Blood Lab Practical', 'ClinicalSubType' => null],
            ['ID' => 248, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T3 Symposium 1: Anaemia: Causes, Symptoms, Investigation and Management - Part 1', 'ClinicalSubType' => null],
            ['ID' => 249, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T3 Symposium 1: Anaemia: Causes, Symptoms, Investigation and Management - Part 2', 'ClinicalSubType' => null],
            ['ID' => 250, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 Living Anatomy/Ultrasound - Heart & Lungs', 'ClinicalSubType' => null],
            ['ID' => 251, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'FMA 2', 'ClinicalSubType' => null],
            ['ID' => 252, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'Phase Leader Forum', 'ClinicalSubType' => null],
            ['ID' => 253, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 PC1 The Effects of Salbutamol and Cardiovascular Function', 'ClinicalSubType' => null],
            ['ID' => 254, 'ModuleCode' => 'BSMS103', 'SessionTitle' => '103 T3 Symposium 2 Haematological Cancer: Focus on Leukaemia - Part 1', 'ClinicalSubType' => null],
            ['ID' => 255, 'ModuleCode' => 'BSMS103', 'SessionTitle' => '103 T3 Symposium 2 Haematological Cancer: Focus on Leukaemia - Part 2', 'ClinicalSubType' => null],
            ['ID' => 256, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 Symposium 1 COPD Symposium - Part 1', 'ClinicalSubType' => null],
            ['ID' => 257, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 Symposium 1 COPD Symposium - Part 2', 'ClinicalSubType' => null],
            ['ID' => 258, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 DR2 Applied Anatomy and Revision', 'ClinicalSubType' => null],
            ['ID' => 259, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'FMA 3', 'ClinicalSubType' => null],
            ['ID' => 260, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 MT1 The physiology of Heart Failure', 'ClinicalSubType' => null],
            ['ID' => 261, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 Symposium\nSudden Death - Part 1', 'ClinicalSubType' => null],
            ['ID' => 262, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 Symposium\nSudden Death - Part 2', 'ClinicalSubType' => null],
            ['ID' => 263, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'FMA 4', 'ClinicalSubType' => null],
            ['ID' => 264, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T2 MT1 Respiratory Failure and Arterial Blood Gases', 'ClinicalSubType' => null],
            ['ID' => 265, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'Inclusivity, language, and professionalism for medical students', 'ClinicalSubType' => null],
            ['ID' => 266, 'ModuleCode' => 'BSMS203', 'SessionTitle' => 'Inclusivity, language, and professionalism for medical students', 'ClinicalSubType' => null],
            ['ID' => 267, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 DR1 Superior Mediastinum', 'ClinicalSubType' => null],
            ['ID' => 268, 'ModuleCode' => 'BSMS103', 'SessionTitle' => 'T1 DR3 Coronary circulation, diaphragm and posterior mediastinum', 'ClinicalSubType' => null],
        ];

        DB::table('MonitoredSessions2026')->insert($sessions);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('MonitoredSessions2026');
    }
}
